name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TAR_OPTIONS: "--no-same-owner"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Run tests
      run: make test

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: npm
        cache-dependency-path: tools/tslint/package-lock.json

    - name: Typecheck TypeScript
      run: make lint-ts
